#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-only
# Build a copy of this plugin pointed at ANOTHER CucaCards server, with its own
# names, so it can be installed next to the production one -- in the Claude
# app, which does not expand variables in .mcp.json, this is the only way to
# aim the plugin somewhere else.
#
#   dev/build-variant.sh <out-dir> <mcp-url> <suffix>
#   e.g. dev/build-variant.sh ../cuca-cards-plugin-dev https://test.example/api/mcp dev
#
# Everything is copied from here and rewritten; the output is never edited by
# hand, so the variant cannot drift from the real plugin.
set -euo pipefail
[ $# -eq 3 ] || { sed -n '8,9p' "$0" >&2; exit 1; }
out="$1"; url="$2"; sfx="$3"
src="$(cd "$(dirname "$0")/.." && pwd)"
mkdir -p "$out"
# Keep the variant's own .git; replace everything else.
find "$out" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
cp -R "$src/.claude-plugin" "$src/skills" "$src/LICENSE" "$out/"
mv "$out/skills/cuca-flashcards" "$out/skills/cuca-flashcards-$sfx"

python3 - "$out" "$url" "$sfx" <<'PY'
import json, sys, pathlib
out, url, sfx = pathlib.Path(sys.argv[1]), sys.argv[2], sys.argv[3]
tag = f"({sfx.upper()}, {url}) "

p = out / ".claude-plugin/plugin.json"
d = json.loads(p.read_text())
d["name"] = f"cuca-cards-{sfx}"
d["description"] = tag + d["description"]
d.pop("repository", None)
p.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")

p = out / ".claude-plugin/marketplace.json"
d = json.loads(p.read_text())
d["name"] = f"cuca-cards-{sfx}"
d["description"] = tag + d["description"]
for pl in d["plugins"]:
    pl["name"] = f"cuca-cards-{sfx}"
    pl["description"] = tag + pl["description"]
p.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")

(out / ".mcp.json").write_text(json.dumps(
    {"mcpServers": {f"cuca-{sfx}": {"type": "http", "url": url}}}, indent=2) + "\n")

s = out / f"skills/cuca-flashcards-{sfx}/SKILL.md"
t = s.read_text()
t = t.replace("name: cuca-flashcards\n", f"name: cuca-flashcards-{sfx}\n", 1)
t = t.replace("description: ", f"description: {tag}", 1)
t = t.replace("skills/cuca-flashcards/scripts", f"skills/cuca-flashcards-{sfx}/scripts")
t = t.replace("**cuca**", f"**cuca-{sfx}**")
s.write_text(t)

(out / "README.md").write_text(
    f"# CucaCards plugin — {sfx} variant\n\n"
    f"Generated by `dev/build-variant.sh` from "
    f"[kamikazebr/cuca-cards-plugin](https://github.com/kamikazebr/cuca-cards-plugin). "
    f"Do not edit here.\n\nMCP server: {url}\n\nLicense: AGPL-3.0-only.\n")
PY
echo "built $out -> $url" >&2
